"""Change_habit_time_measure

Revision ID: 00c9e7cab527
Revises: c2e9d2cbfadd
Create Date: 2025-06-14 23:07:47.020665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00c9e7cab527'
down_revision: Union[str, None] = 'c2e9d2cbfadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('days_of_week', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('times_of_day', sa.String(), nullable=True))
    op.alter_column('habits', 'target_times',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('habits', 'time_of_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('time_of_day', postgresql.TIME(), autoincrement=False, nullable=True))
    op.alter_column('habits', 'target_times',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('habits', 'times_of_day')
    op.drop_column('habits', 'days_of_week')
    # ### end Alembic commands ###
