"""add_user_to_habit_tracking_log

Revision ID: 4e2154ac9b59
Revises: 00c9e7cab527
Create Date: 2025-06-15 19:30:07.899893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2154ac9b59'
down_revision: Union[str, None] = '00c9e7cab527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_tracking_logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'habit_tracking_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit_tracking_logs', type_='foreignkey')
    op.drop_column('habit_tracking_logs', 'user_id')
    # ### end Alembic commands ###
