"""rename_icon_to_color_in_habit_category

Revision ID: c2e9d2cbfadd
Revises: 9a5a0b53182b
Create Date: 2025-06-14 20:18:39.814215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e9d2cbfadd'
down_revision: Union[str, None] = '9a5a0b53182b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_categories', sa.Column('color', sa.String(length=50), nullable=True))
    op.drop_column('habit_categories', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_categories', sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('habit_categories', 'color')
    # ### end Alembic commands ###
